def remote = [:]
remote.name = "jenkins"
remote.host = "192.168.88.254"
remote.allowAnyHosts = true

node {
    withCredentials([sshUserPrivateKey(credentialsId: 'repozitarium', keyFileVariable: 'identity', usernameVariable: 'userName')]) {
        remote.user = userName
        remote.identityFile = identity
        stage("SSH Steps Rocks!") {
//             writeFile file: 'abc.sh', text: 'ls'
            sshCommand remote: remote, command: 'sh /home/zavx0z/projects/bib/docker/startUbuntu.sh'
//             sshPut remote: remote, from: 'abc.sh', into: '.'
//             sshGet remote: remote, from: 'abc.sh', into: 'bac.sh', override: true
//             sshScript remote: remote, script: 'abc.sh'
//             sshRemove remote: remote, path: 'abc.sh'
        }
    }
}