def remote = [:]
remote.name = "jenkins"
remote.host = "192.168.88.254"
remote.allowAnyHosts = true

node {
    withCredentials([sshUserPrivateKey(credentialsId: 'repozitarium', keyFileVariable: 'identity', usernameVariable: 'userName')]) {
        remote.user = userName
        remote.identityFile = identity
        stage("остановить все контейнеры") {
            sshCommand remote: remote, command: 'docker stop $(docker ps -a -q)', failOnError: false
        }
        stage("удалить все контейнеры") {
            sshCommand remote: remote, command: 'docker rm $(docker ps -a -q)', failOnError: false
        }
        stage("удалить все изображения") {
            sshCommand remote: remote, command: 'docker rmi -f $(docker images -aq)', failOnError: false
        }
        stage("развертывание образа bib") {
            sshCommand remote: remote, command: 'sh /home/zavx0z/projects/bib/docker/startUbuntu.sh'
        }
        stage("Запуск VNC-viewer в Google Chrome") {
            sshCommand remote: remote, command: 'google-chrome http://localhost:6080'
        }
    }
}
//             writeFile file: 'abc.sh', text: 'ls'
//             sshPut remote: remote, from: 'abc.sh', into: '.'
//             sshGet remote: remote, from: 'abc.sh', into: 'bac.sh', override: true
//             sshScript remote: remote, script: 'abc.sh'
//             sshRemove remote: remote, path: 'abc.sh'
